21:19:12 - ERR - get - ('Error en el método get de ProfileService: ProfileComponent.get_profile() takes 0 positional arguments but 1 was given',)
21:22:33 - ERR - get - ('Error en el método get de ProfileService: ProfileComponent.get_profile() takes 0 positional arguments but 1 was given',)
21:22:48 - ERR - getRecords - (UndefinedTable('no existe la relación «dawa.perfil»\nLINE 14:             LEFT JOIN dawa.PERFIL p ON u.ID = p.user_id\n                               ^\n'),)
21:23:59 - ERR - getRecords - (UndefinedTable('no existe la relación «dawa.perfil»\nLINE 14:             LEFT JOIN dawa.PERFIL p ON u.ID = p.user_id\n                               ^\n'),)
21:24:08 - ERR - get - ("Error en el método get de ProfileService: name 'HandleLogs' is not defined",)
21:24:36 - ERR - getRecords - (UndefinedColumn('no existe la columna d.vive_en\nLINE 4:                    d.vive_en, \n                           ^\n'),)
22:54:25 - ERR - getRecords - (OperationalError('connection to server at "192.168.100.32", port 5432 failed: Connection timed out (0x0000274C/10060)\n\tIs the server running on that host and accepting TCP/IP connections?\n'),)
22:54:25 - ERR - login - (UnboundLocalError("cannot access local variable 'cursor' where it is not associated with a value"),)
22:57:15 - ERR - getRecords - (OperationalError('connection to server at "192.168.100.32", port 5432 failed: Connection timed out (0x0000274C/10060)\n\tIs the server running on that host and accepting TCP/IP connections?\n'),)
22:57:41 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
22:58:26 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:00:31 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:07:06 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:08:01 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:08:42 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:09:41 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:12:11 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:12:13 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:12:14 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:12:19 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:15:05 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:15:09 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:16:13 - ERR - getRecords - (UnicodeDecodeError('utf-8', b'connection to server at "192.168.100.10", port 5432 failed: FATAL:  no hay una l\xednea en pg_hba.conf para \xab192.168.100.10\xbb, usuario \xabpostgres\xbb, base de datos \xabpostgres\xbb, sin cifrado\n', 80, 81, 'invalid continuation byte'),)
23:21:12 - ERR - getRecords - (OperationalError('connection to server at "192.168.100.10", port 5432 failed: FATAL:  no pg_hba.conf entry for host "192.168.100.10", user "postgres", database "postgres", no encryption\n'),)
23:22:53 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.USUARIO u \n                         ^\n'),)
23:24:20 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.USUARIO u \n                         ^\n'),)
23:24:21 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.USUARIO u \n                         ^\n'),)
23:24:22 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.USUARIO u \n                         ^\n'),)
23:26:23 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.USUARIO u \n                         ^\n'),)
23:36:56 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:36:57 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:36:58 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:36:59 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:37:04 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:37:22 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:38:02 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:40:54 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:40:54 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:40:55 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 3:             FROM dawa.usuario u \n                         ^\n'),)
23:42:00 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 1: Select * from dawa.usuario where username = \'spgb\' and contr...\n                      ^\n'),)
23:42:01 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 1: Select * from dawa.usuario where username = \'spgb\' and contr...\n                      ^\n'),)
23:45:29 - ERR - getRecords - (UndefinedTable('relation "dawa.usuario" does not exist\nLINE 1: Select * from dawa.usuario where username = \'spgb\' and contr...\n                      ^\n'),)
23:47:23 - ERR - getRecords - (UndefinedTable('relation "usuario" does not exist\nLINE 1: Select * from usuario where username = \'spgb\' and contraseni...\n                      ^\n'),)
23:47:28 - ERR - getRecords - (UndefinedTable('relation "usuario" does not exist\nLINE 1: Select * from usuario where username = \'spgb\' and contraseni...\n                      ^\n'),)
23:52:07 - ERR - getRecords - (UndefinedTable("no existe la relación «dawa.usuario»\nLINE 1: Select * from dawa.usuario where username = 'spgb' and contr...\n                      ^\n"),)
23:53:01 - ERR - login - (KeyError('usuario_id'),)
